### ISSUE TITLE
Release PHP 8.1 version

### ISSUE THREAD

**Issue by garciasdos** [imanghafoori1/laravel-decorator#22]
Hello there,

First of all congratulations for your awesome package 🎉 

I am wondering to use it in one of my PHP 8.1 projects but I see that there aren't any releases supporting PHP 8.1 / Laravel 9 yet. 
Are you considering on releasing a PHP 8.1 major version? Is there something breaking because of this upgrade?

Thank you!!

**Comment by imanghafoori1** [comment]
I think you can install the latest version now, with no problem.

**Comment by garciasdos** [comment]
The think is that it's dangerous to set my dependency to `dev-master`, since a future breaking change can be added. Think that releasing a new version is a more confident option

**Comment by imanghafoori1** [comment]
I mean you can install the `v1.0.5‍‍‍`

**Comment by imanghafoori1** [comment]
Sorry, I think version ‍‍`1.0.7` is now ready for you.
